### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by t-cool**
It seems we need to set the Content-Type on the HTML page to avoid the error as bellow:  "Invalid regular expression: /.../: Range out of order in character class."

### CODE REVIEW

**Comment by tiye** [comment]
I was testing the page on Mac Chrome and it looked cool. What’s you environment?

**Comment by t-cool** [comment]
Hi. I tested on Mac (High Sierra 10.13.6) Chrome and Firefox.  I faced with the error as I wrote.

**Comment by tiye** [comment]
“Range out of order in character class” is a JavaScript error. It might come from an extension, if we are running in the same env. It’s unlikely an error thrown directly from Chrome.

**Comment by t-cool** [comment]
I agree.  I thought it came from the extension, so I tested on Firefox too.  I read this article and I was able to deal with the error by adding the charset as meta data.  

https://stackoverflow.com/questions/31225606/babel-with-browser-js-getting-uncaught-syntaxerror-invalid-regular-expression

**Comment by tiye** [comment]
anyways `charset="utf-8"` fixes.

**Comment by t-cool** [comment]
Yes!  I've just started to learn Clojure(Script) recently.  Your articles on Medium are so valuable to me.

**Comment by tiye** [comment]
Thanks. Reach us on [ClojureVerse](https://clojureverse.org) and [Twitter](https://twitter.com/jiyinyiyong) if you need help on ClojureScript compiling or JavaScript bundling.

**Comment by t-cool** [comment]
Thank you for telling me the useful information.  I followed your account on Twitter!

**Pull request merged**
